package Telas;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brandon Carlos
 */
public class ConsultaPorMarca extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaPorMarca
     */
    public ConsultaPorMarca() {
        initComponents();
        
        setTitle("Consultando por marca");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Marca = new javax.swing.JTextField();
        btn_Procurar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPorMarca = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 153, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta por marca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 45));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite a marca:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        txt_Marca.setBackground(new java.awt.Color(23, 153, 255));
        txt_Marca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_Marca.setForeground(new java.awt.Color(255, 255, 255));
        txt_Marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Marca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, -1));

        btn_Procurar.setBackground(new java.awt.Color(23, 153, 255));
        btn_Procurar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Procurar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Procurar.setText("Procurar");
        btn_Procurar.setBorder(null);
        btn_Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Procurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        TabelaPorMarca.setBackground(new java.awt.Color(23, 153, 255));
        TabelaPorMarca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelaPorMarca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        TabelaPorMarca.setForeground(new java.awt.Color(255, 255, 255));
        TabelaPorMarca.setModel(new DefaultTableModel());
        jScrollPane1.setViewportView(TabelaPorMarca);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 760, 200));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Veiculos cadastrados");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 700, -1));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background3.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 780, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProcurarActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try{
            ((DefaultTableModel)TabelaPorMarca.getModel()).setRowCount(0);
            ((DefaultTableModel)TabelaPorMarca.getModel()).setColumnCount(8);
            
            Object cabecalhos[] = {"Id_Veiculo", "Preço", "Ano", "Marca", "Modelo", "Placa", "Estado", "Loja Veiculo"};
            ((DefaultTableModel)TabelaPorMarca.getModel()).setColumnIdentifiers(cabecalhos);
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funciona;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT * FROM veiculo WHERE marca = ? ";
            pst = con.prepareStatement(query);
            pst.setString(1, txt_Marca.getText());
            rs = pst.executeQuery();
            
            Object dados[] = new Object[8];
            while(rs.next()){
                int id_veiculo = rs.getInt("id_veiculo");
                float preco = rs.getFloat("preco");
                Date data = rs.getDate("ano");
                String marca = rs.getString("marca");
                String modelo = rs.getString("modelo");
                String placah = rs.getString("placa");
                String estado = rs.getString("estado");
                String loja = rs.getString("loja_veic");
                
                dados[0] = id_veiculo;
                dados[1] = preco;
                dados[2] = data;
                dados[3] = marca;
                dados[4] = modelo;
                dados[5] = placah;
                dados[6] = estado;
                dados[7] = loja;
                ((DefaultTableModel)TabelaPorMarca.getModel()).addRow(dados);
               
            }
        
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados. " + e1);
            
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Não foi possivel mostrar o veiculo. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
                
            }
            catch(Exception e3){
            
            }
            
        }
           
    }//GEN-LAST:event_btn_ProcurarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaPorMarca;
    private javax.swing.JButton btn_Procurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
