/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Carlos
 */
public class EditarEstado extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarEstado
     */
    public EditarEstado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_NomeEstado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_AntigoIdEstado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Abreviatura = new javax.swing.JTextField();
        btn_Editar = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 153, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite a abreviatura:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        txt_NomeEstado.setBackground(new java.awt.Color(23, 153, 255));
        txt_NomeEstado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_NomeEstado.setForeground(new java.awt.Color(255, 255, 255));
        txt_NomeEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NomeEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_NomeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Digite a nova abreviatura:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 90, 210, 20));

        txt_AntigoIdEstado.setBackground(new java.awt.Color(23, 153, 255));
        txt_AntigoIdEstado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_AntigoIdEstado.setForeground(new java.awt.Color(255, 255, 255));
        txt_AntigoIdEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_AntigoIdEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_AntigoIdEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Digite o novo estado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txt_Abreviatura.setBackground(new java.awt.Color(23, 153, 255));
        txt_Abreviatura.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_Abreviatura.setForeground(new java.awt.Color(255, 255, 255));
        txt_Abreviatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Abreviatura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Abreviatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 60, -1));

        btn_Editar.setBackground(new java.awt.Color(23, 153, 255));
        btn_Editar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Editar.setText("Editar");
        btn_Editar.setBorder(null);
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 30));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background3.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con =  DriverManager.getConnection(url, "root", "");
            String alterar = "UPDATE estado SET id_abreviatura = ?, nome_estado = ? WHERE id_abreviatura = ?";
            pst = con.prepareStatement(alterar);
            pst.setString(1, txt_Abreviatura.getText());
            pst.setString(2, txt_NomeEstado.getText());
            pst.setString(3, txt_AntigoIdEstado.getText());
            int retorno = pst.executeUpdate();
            if(retorno > 0){
                JOptionPane.showMessageDialog(null, "Estado editado com sucesso.");
            }
       
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao editar o estado. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
            }
            catch(Exception e3){
            
            }
            
        }
        
    }//GEN-LAST:event_btn_EditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Abreviatura;
    private javax.swing.JTextField txt_AntigoIdEstado;
    private javax.swing.JTextField txt_NomeEstado;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
