package Telas;
import java.sql.*;
import javax.swing.JOptionPane;
//import o javax.swing.DefaultListModel
import javax.swing.DefaultListModel;
//MODIFICAÇÃO
import java.sql.*;

/**
 *
 * @author Brandon Carlos
 */
public class EditarVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarVeiculo
     */
    public EditarVeiculo() {
        initComponents();
        
        setTitle("Editando veiculo");
        
        //fazendo aparecer na lista as "marcas"
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT nome_marca FROM marca_modelo";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String marca = rs.getString("nome_marca");
                DefaultListModel modelo = (DefaultListModel)(ListaMarca.getModel());
                modelo.addElement(marca);             
            }           

        }catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao mostrar as marcas. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        preco = new javax.swing.JLabel();
        txt_idVeiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_preco = new javax.swing.JTextField();
        placa = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        ano = new javax.swing.JLabel();
        txt_ano = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaLoja = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaMarca = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaModelo = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaEstado = new javax.swing.JList<>();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editando veiculo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(23, 153, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        preco.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        preco.setForeground(new java.awt.Color(255, 255, 255));
        preco.setText("Digite o preço:");
        getContentPane().add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        txt_idVeiculo.setBackground(new java.awt.Color(23, 153, 255));
        txt_idVeiculo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_idVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        txt_idVeiculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idVeiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_idVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 50, 22));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite o ID do veiculo que vai editar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txt_preco.setBackground(new java.awt.Color(23, 153, 255));
        txt_preco.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_preco.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_preco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 125, 120, 22));

        placa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        placa.setForeground(new java.awt.Color(255, 255, 255));
        placa.setText("Digite a placa:");
        getContentPane().add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txt_placa.setBackground(new java.awt.Color(23, 153, 255));
        txt_placa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_placa.setForeground(new java.awt.Color(255, 255, 255));
        txt_placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_placa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 120, 22));

        ano.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ano.setForeground(new java.awt.Color(255, 255, 255));
        ano.setText("Digite o ano:");
        getContentPane().add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        txt_ano.setBackground(new java.awt.Color(23, 153, 255));
        txt_ano.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_ano.setForeground(new java.awt.Color(255, 255, 255));
        txt_ano.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ano.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 125, 120, 22));

        ListaLoja.setBackground(new java.awt.Color(23, 153, 255));
        ListaLoja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaLoja.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ListaLoja.setForeground(new java.awt.Color(255, 255, 255));
        ListaLoja.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(ListaLoja);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 130, 140));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selecione a marca:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selecione a loja:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        ListaMarca.setBackground(new java.awt.Color(23, 153, 255));
        ListaMarca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaMarca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ListaMarca.setForeground(new java.awt.Color(255, 255, 255));
        ListaMarca.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(ListaMarca);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 110));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selecione o modelo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        ListaModelo.setBackground(new java.awt.Color(23, 153, 255));
        ListaModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaModelo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ListaModelo.setForeground(new java.awt.Color(255, 255, 255));
        ListaModelo.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(ListaModelo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 130, 110));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Selecione o estado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        ListaEstado.setBackground(new java.awt.Color(23, 153, 255));
        ListaEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaEstado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ListaEstado.setForeground(new java.awt.Color(255, 255, 255));
        ListaEstado.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(ListaEstado);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 140, 110));

        btn3.setBackground(new java.awt.Color(23, 153, 255));
        btn3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("Ver loja");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 140, -1));

        btn1.setBackground(new java.awt.Color(23, 153, 255));
        btn1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("Ver modelo");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, -1));

        btn2.setBackground(new java.awt.Color(23, 153, 255));
        btn2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("Ver estado");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 130, -1));

        btn_Editar.setBackground(new java.awt.Color(23, 153, 255));
        btn_Editar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_Editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Editar.setText("Editar");
        btn_Editar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 110, 50));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background3.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con =  DriverManager.getConnection(url, "root", "");
            String alterar = "UPDATE veiculo SET preco = ?, ano = ?, marca = ?, modelo = ?, placa = ?, estado = ?, loja_veic = ? WHERE id_veiculo = ?";
            pst = con.prepareStatement(alterar);
            pst.setFloat(1, Float.parseFloat(txt_preco.getText()));
            String dia = txt_ano.getText().substring(0, 2);
            String mes = txt_ano.getText().substring(3, 5);
            String ano = txt_ano.getText().substring(6);
            String dataParaMysql = ano + "-" + mes + "-" + dia;
            
            pst.setString(2, dataParaMysql);
            pst.setString(3, ListaMarca.getSelectedValue());
            pst.setString(4, ListaModelo.getSelectedValue());
            pst.setString(5, txt_placa.getText());
            pst.setString(6, ListaEstado.getSelectedValue());
            pst.setString(7, ListaLoja.getSelectedValue());
            pst.setInt(8, Integer.parseInt(txt_idVeiculo.getText()));
            int retorno = pst.executeUpdate();
            if(retorno > 0){
                JOptionPane.showMessageDialog(null, "Veiculo editado com sucesso.");
            }
       
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao editar o veiculo. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
            }
            catch(Exception e3){
            
            }
            
        }
    
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        int selecionado = ListaMarca.getSelectedIndex() + 1;
        
        String filtro = "";
        if(selecionado == 1){
            filtro = "WHERE nome_marca = 'Chevrolet'";
        }
        
        if(selecionado == 2){
            filtro = "WHERE nome_modelo = 'Uno'";
        }
        
        if(selecionado == 3){
            filtro = "WHERE nome_modelo = 'Fiesta'";
        }
        
        if(selecionado == 4){
            filtro = "WHERE nome_modelo = 'Corolla'";
        }
        
        if(selecionado == 5){
            filtro = "WHERE nome_modelo = 'Gol'";
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT * FROM marca_modelo " + filtro;
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String modelo = rs.getString("nome_modelo");
                DefaultListModel modelito = (DefaultListModel)(ListaModelo.getModel());
                modelito.addElement(modelo);
                modelito.addElement("");
            }
            
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dado. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao mostrar os modelos da marca selecionada. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT * FROM estado";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String abreviatura = rs.getString("id_abreviatura");
                DefaultListModel modelo = (DefaultListModel)(ListaEstado.getModel());
                modelo.addElement(abreviatura);

            }
            
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dado. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao mostrar os estados. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT * FROM loja";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String loja = rs.getString("id_loja");
                DefaultListModel modelo = (DefaultListModel)(ListaLoja.getModel());
                modelo.addElement(loja);
            }
            
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dado. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao mostrar as lojas. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
    }//GEN-LAST:event_btn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaEstado;
    private javax.swing.JList<String> ListaLoja;
    private javax.swing.JList<String> ListaMarca;
    private javax.swing.JList<String> ListaModelo;
    private javax.swing.JLabel ano;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel preco;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_idVeiculo;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
