package Telas;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Carlos
 */
public class EliminarVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarVeiculo
     */
    public EliminarVeiculo() {
        initComponents();
        
        setTitle("Eliminar veiculo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_idVeiculo = new javax.swing.JTextField();
        btn_Eliminar = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminando veiculo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 20));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(23, 153, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 44));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite o id do veiculo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        txt_idVeiculo.setBackground(new java.awt.Color(23, 153, 255));
        txt_idVeiculo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_idVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        txt_idVeiculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idVeiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_idVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, -1));

        btn_Eliminar.setBackground(new java.awt.Color(23, 153, 255));
        btn_Eliminar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setBorder(null);
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 40));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background3.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 410, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
       
        Connection con = null;
        PreparedStatement pst = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funciona;
            con = DriverManager.getConnection(url, "root", "");
            String del = "DELETE FROM veiculo WHERE id_veiculo = ?";
            pst = con.prepareStatement(del);
            pst.setString(1, txt_idVeiculo.getText());
            int retorno = pst.executeUpdate();
            
            if(retorno > 0){
                JOptionPane.showMessageDialog(null, "Veiculo eliminado com sucesso!");              
            }
             
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados." + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao eliminar veiculo." + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
    }//GEN-LAST:event_btn_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_idVeiculo;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
