package Telas;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Carlos
 */
public class EliminarEstado extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarEstado
     */
    public EliminarEstado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_IdAbreviatura = new javax.swing.JTextField();
        btn_Eliminar = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 153, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 45));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite a abreviatura:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txt_IdAbreviatura.setBackground(new java.awt.Color(23, 153, 255));
        txt_IdAbreviatura.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_IdAbreviatura.setForeground(new java.awt.Color(255, 255, 255));
        txt_IdAbreviatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_IdAbreviatura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_IdAbreviatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdAbreviaturaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_IdAbreviatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 60, -1));

        btn_Eliminar.setBackground(new java.awt.Color(23, 153, 255));
        btn_Eliminar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background3.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 390, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IdAbreviaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdAbreviaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdAbreviaturaActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con =  DriverManager.getConnection(url, "root", "");
            String remover = "DELETE FROM estado WHERE id_abreviatura = ?";
            pst = con.prepareStatement(remover);
            pst.setString(1, txt_IdAbreviatura.getText());
            
            int retorno = pst.executeUpdate();
            if(retorno > 0){
                JOptionPane.showMessageDialog(null, "Abreviatura(Estado), removido com sucesso. ");
            }
       
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao remover Abreviatura(Estado). " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
            }
            catch(Exception e3){
            
            }
            
        }
        
    }//GEN-LAST:event_btn_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_IdAbreviatura;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
