/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Brandon Carlos
 */
public class Estados extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estados
     */
    public Estados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        InserirEstado = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        EditarEstado = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        EliminarEstado = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(65, 45));
        jToolBar1.setMinimumSize(new java.awt.Dimension(65, 45));
        jToolBar1.add(jSeparator1);

        InserirEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar.png"))); // NOI18N
        InserirEstado.setFocusable(false);
        InserirEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InserirEstado.setMaximumSize(new java.awt.Dimension(65, 45));
        InserirEstado.setMinimumSize(new java.awt.Dimension(65, 45));
        InserirEstado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        InserirEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirEstadoActionPerformed(evt);
            }
        });
        jToolBar1.add(InserirEstado);
        jToolBar1.add(jSeparator2);

        EditarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        EditarEstado.setFocusable(false);
        EditarEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarEstado.setMaximumSize(new java.awt.Dimension(65, 45));
        EditarEstado.setMinimumSize(new java.awt.Dimension(65, 45));
        EditarEstado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEstadoActionPerformed(evt);
            }
        });
        jToolBar1.add(EditarEstado);
        jToolBar1.add(jSeparator3);

        EliminarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remover.png"))); // NOI18N
        EliminarEstado.setFocusable(false);
        EliminarEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarEstado.setMaximumSize(new java.awt.Dimension(65, 45));
        EliminarEstado.setMinimumSize(new java.awt.Dimension(65, 45));
        EliminarEstado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEstadoActionPerformed(evt);
            }
        });
        jToolBar1.add(EliminarEstado);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 784, 45));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background-menus.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 470));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 470));

        jMenu1.setText("Opções");

        jMenuItem1.setText("Inserir estado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Editar estado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar estado");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        InserirEstado inserirEstado = new InserirEstado();
        wallpaper.add(inserirEstado);
        inserirEstado.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        EditarEstado editarEstado = new EditarEstado();
        wallpaper.add(editarEstado);
        editarEstado.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        EliminarEstado eliminarEstado = new EliminarEstado();
        wallpaper.add(eliminarEstado);
        eliminarEstado.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void InserirEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirEstadoActionPerformed
        InserirEstado inserirEstado = new InserirEstado();
        wallpaper.add(inserirEstado);
        inserirEstado.setVisible(true);
    }//GEN-LAST:event_InserirEstadoActionPerformed

    private void EditarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEstadoActionPerformed
        
        EditarEstado editarEstado = new EditarEstado();
        wallpaper.add(editarEstado);
        editarEstado.setVisible(true);
        
    }//GEN-LAST:event_EditarEstadoActionPerformed

    private void EliminarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEstadoActionPerformed
        
        EliminarEstado eliminarEstado = new EliminarEstado();
        wallpaper.add(eliminarEstado);
        eliminarEstado.setVisible(true);
        
    }//GEN-LAST:event_EliminarEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarEstado;
    private javax.swing.JButton EliminarEstado;
    private javax.swing.JButton InserirEstado;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
