package Telas;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import java.util.Date;
/**
 *
 * @author Brandon Carlos
 */
public class InserirVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form InserirVeiculo
     */
    public InserirVeiculo() {
        initComponents();
    
        setTitle("Inserindo veiculo");
        
        //fazendo aparecer na lista as "marcas"
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT nome_marca FROM marca_modelo";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String marca = rs.getString("nome_marca");
                DefaultListModel modelo = (DefaultListModel)(ListaMarca.getModel());
                modelo.addElement(marca);             
            }           

        }catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao mostrar as marcas. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txt_placa1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnInserir = new javax.swing.JButton();
        txt_placa = new javax.swing.JTextField();
        txt_ano = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaMarca = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaModelo = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaEstado = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaLoja = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Preencha os dados para inserir o veiculo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 10, 720, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(23, 153, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        txt_placa1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_placa1.setForeground(new java.awt.Color(255, 255, 255));
        txt_placa1.setText("Digite a placa:");
        getContentPane().add(txt_placa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selecione a marca:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selecione o modelo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Digite o ano:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Digite o preço:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Selecione o estado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Selecione a loja:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        BtnInserir.setBackground(new java.awt.Color(23, 153, 255));
        BtnInserir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        BtnInserir.setForeground(new java.awt.Color(255, 255, 255));
        BtnInserir.setText("Inserir");
        BtnInserir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 110, 50));

        txt_placa.setBackground(new java.awt.Color(23, 153, 255));
        txt_placa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_placa.setForeground(new java.awt.Color(255, 255, 255));
        txt_placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_placa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, 120, 22));

        txt_ano.setBackground(new java.awt.Color(23, 153, 255));
        txt_ano.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_ano.setForeground(new java.awt.Color(255, 255, 255));
        txt_ano.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ano.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 85, 100, 22));

        txt_preco.setBackground(new java.awt.Color(23, 153, 255));
        txt_preco.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_preco.setForeground(new java.awt.Color(255, 255, 255));
        txt_preco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_preco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 85, 110, 22));

        ListaMarca.setBackground(new java.awt.Color(23, 153, 255));
        ListaMarca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaMarca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ListaMarca.setForeground(new java.awt.Color(255, 255, 255));
        ListaMarca.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(ListaMarca);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 110));

        ListaModelo.setBackground(new java.awt.Color(23, 153, 255));
        ListaModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaModelo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ListaModelo.setForeground(new java.awt.Color(255, 255, 255));
        ListaModelo.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(ListaModelo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, 110));

        ListaEstado.setBackground(new java.awt.Color(23, 153, 255));
        ListaEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaEstado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ListaEstado.setForeground(new java.awt.Color(255, 255, 255));
        ListaEstado.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(ListaEstado);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 140, 110));

        ListaLoja.setBackground(new java.awt.Color(23, 153, 255));
        ListaLoja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaLoja.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ListaLoja.setForeground(new java.awt.Color(255, 255, 255));
        ListaLoja.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(ListaLoja);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 130, 140));

        jButton1.setBackground(new java.awt.Color(23, 153, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver loja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 140, -1));

        jButton2.setBackground(new java.awt.Color(23, 153, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ver modelo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, -1));

        jButton3.setBackground(new java.awt.Color(23, 153, 255));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ver estado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, -1));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background3.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 720, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserirActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String insertando = "INSERT INTO veiculo (preco, ano, marca, modelo, placa, estado, loja_veic) VALUES(?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(insertando);
            pst.setFloat(1, Float.parseFloat(txt_preco.getText()));
            String dia = txt_ano.getText().substring(0, 2);
            String mes = txt_ano.getText().substring(3, 5);
            String ano = txt_ano.getText().substring(6);
            String dataParaMysql = ano + "-" + mes + "-" + dia;
            
            pst.setString(2, dataParaMysql);
            pst.setString(3, ListaMarca.getSelectedValue());
            pst.setString(4, ListaModelo.getSelectedValue());
            pst.setString(5, txt_placa.getText());
            pst.setString(6, ListaEstado.getSelectedValue());
            pst.setString(7, ListaLoja.getSelectedValue());
            
            int retorno = pst.executeUpdate();
            
            
            if(retorno > 0){
                JOptionPane.showMessageDialog(null, "Veiculo inserido com sucesso. ");
            }
                    
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao inserir o veiculo. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;                  
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                    
            }
            catch(Exception e3){
            
            }
        }
        
        
        
    }//GEN-LAST:event_BtnInserirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        int selecionado = ListaMarca.getSelectedIndex() + 1;
        
        String filtro = "";
        if(selecionado == 1){
            filtro = "WHERE nome_marca = 'Chevrolet'";
        }
        
        if(selecionado == 2){
            filtro = "WHERE nome_marca = 'Fiat'";
        }
        
        if(selecionado == 3){
            filtro = "WHERE nome_marca = 'Ford'";
        }
        
        if(selecionado == 4){
            filtro = "WHERE nome_marca = 'Toyota'";
        }
        
        if(selecionado == 5){
            filtro = "WHERE nome_marca = 'Volkswagen'";
        }
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT * FROM marca_modelo " + filtro;
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String modelo = rs.getString("nome_modelo");
                DefaultListModel modelito = (DefaultListModel)(ListaModelo.getModel());
                modelito.addElement(modelo);
                modelito.addElement("");
            }
            
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dado. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao mostrar os modelos da marca selecionada. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT * FROM estado";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String abreviatura = rs.getString("id_abreviatura");
                DefaultListModel modelo = (DefaultListModel)(ListaEstado.getModel());
                modelo.addElement(abreviatura);

            }
            
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dado. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao mostrar os estados. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String query = "SELECT * FROM loja";
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String loja = rs.getString("id_loja");
                DefaultListModel modelo = (DefaultListModel)(ListaLoja.getModel());
                modelo.addElement(loja);
            }
            
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dado. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao mostrar as lojas. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                if(rs != null){
                    rs.close();
                    rs = null;
                }
            }
            catch(Exception e3){
            
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInserir;
    private javax.swing.JList<String> ListaEstado;
    private javax.swing.JList<String> ListaLoja;
    private javax.swing.JList<String> ListaMarca;
    private javax.swing.JList<String> ListaModelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JLabel txt_placa1;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
