/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Carlos
 */
public class InserirMarcasModelos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InserirMarcasModelos
     */
    public InserirMarcasModelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_NomeModelo = new javax.swing.JTextField();
        txt_NomeMarca = new javax.swing.JTextField();
        btn_Inserir = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inserir MarcasModelos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 410, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 45));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite o nome do modelo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Digite o nome da marca:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txt_NomeModelo.setBackground(new java.awt.Color(23, 153, 255));
        txt_NomeModelo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_NomeModelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_NomeModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NomeModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_NomeModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 160, -1));

        txt_NomeMarca.setBackground(new java.awt.Color(23, 153, 255));
        txt_NomeMarca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_NomeMarca.setForeground(new java.awt.Color(255, 255, 255));
        txt_NomeMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NomeMarca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_NomeMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, -1));

        btn_Inserir.setBackground(new java.awt.Color(23, 153, 255));
        btn_Inserir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Inserir.setForeground(new java.awt.Color(255, 255, 255));
        btn_Inserir.setText("Inserir");
        btn_Inserir.setBorder(null);
        btn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InserirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background3.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 410, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InserirActionPerformed
        
        Connection con = null;
        PreparedStatement pst = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
            con = DriverManager.getConnection(url, "root", "");
            String insertando = "INSERT INTO marca_modelo (nome_marca, nome_modelo) VALUES(?, ?)";
            pst = con.prepareStatement(insertando);
            pst.setString(1, txt_NomeMarca.getText());
            pst.setString(2, txt_NomeModelo.getText());           
            int retorno = pst.executeUpdate();
                       
            if(retorno > 0){
                JOptionPane.showMessageDialog(null, "Marca e Modelo inseridos com sucesso. ");
            }
                    
        }
        catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Verifique sua base de dados. " + e1);
        }
        catch(Exception e2){
            JOptionPane.showMessageDialog(null, "Erro ao inserir Marca e Modelo. " + e2);
        }
        finally{
            try{
                if(con != null){
                    con.close();
                    con = null;                  
                }
                if(pst != null){
                    pst.close();
                    pst = null;
                }
                    
            }
            catch(Exception e3){
            
            }
        }
        
    }//GEN-LAST:event_btn_InserirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Inserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_NomeMarca;
    private javax.swing.JTextField txt_NomeModelo;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
