package Telas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Carlos
 */
public class Login extends javax.swing.JFrame {

    public static String user = "";
    String pass = "";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        setTitle("Sistema Detran");
        setSize(400, 550);
        setLocationRelativeTo(null);//aki é para centralizar a interface no meio da tela
        setResizable(false);

        //Iremos adaptar a imagem para um jLabel
        //1° passo procurar a imagem;
        ImageIcon background = new ImageIcon("src/Imagens/background.jpg");
        //2° passo adaptar ao jLabel
        Icon imagem = new ImageIcon(background.getImage().getScaledInstance(wallpaper.getWidth(), wallpaper.getHeight(), Image.SCALE_DEFAULT));
        //3° passo adicionar a "imagem" já adaptada no jLabel
        wallpaper.setIcon(imagem);

        //Agora faremos o mesmo para a segunda imagem;
        ImageIcon background2 = new ImageIcon("src/Imagens/detran.jpg");
        Icon imagem2 = new ImageIcon(background2.getImage().getScaledInstance(wallpaper2.getWidth(), wallpaper2.getHeight(), Image.SCALE_DEFAULT));
        wallpaper2.setIcon(imagem2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        btn = new javax.swing.JButton();
        wallpaper2 = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuario.setBackground(new java.awt.Color(23, 153, 255));
        txt_usuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 330, 210, -1));

        txt_senha.setBackground(new java.awt.Color(23, 153, 255));
        txt_senha.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_senha.setForeground(new java.awt.Color(255, 255, 255));
        txt_senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_senha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 370, 210, -1));

        btn.setBackground(new java.awt.Color(23, 153, 255));
        btn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("Entrar");
        btn.setBorder(null);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 420, 210, 40));
        getContentPane().add(wallpaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 250));
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed

        user = txt_usuario.getText().trim();
        pass = txt_senha.getText().trim();

        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        if (!user.equals("") && !pass.equals("")) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                String url = "jdbc:mysql://localhost/cad_detran" + "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo";//Nesta linha teve ERRO, tive que por o "?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo"; para funcionar;
                con = DriverManager.getConnection(url, "root", "");
                String query = "SELECT login FROM usuario WHERE login = '" + user + "' and senha = '" + pass + "'";
                pst = con.prepareStatement(query);
                rs = pst.executeQuery();

                if (rs.next()) {
                    dispose();
                    Principal pr = new Principal();
                    pr.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Dados de acesso incorretos.");
                    txt_usuario.setText("");
                    txt_senha.setText("");
                }

            } catch (SQLException e1) {

            } catch (Exception e2) {

            } finally {
                try {
                    
                    if(con != null){
                        con.close();
                        con = null;
                    }
                    if(pst != null){
                        pst.close();
                        pst = null;
                    }
                    if(rs != null){
                        rs.close();
                        rs = null;                       
                    }
                    
                } catch (Exception e3) {

                }    
            }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        }
        
        
    }//GEN-LAST:event_btnActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JLabel wallpaper;
    private javax.swing.JLabel wallpaper2;
    // End of variables declaration//GEN-END:variables
}
