/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Brandon Carlos
 */
public class MarcasModelos extends javax.swing.JInternalFrame {

    /**
     * Creates new form MarcasModelos
     */
    public MarcasModelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        InserirMarcasModelos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        EditarMarcasModelos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        EliminarMarcasModelos = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(65, 45));
        jToolBar1.setMinimumSize(new java.awt.Dimension(65, 45));
        jToolBar1.add(jSeparator1);

        InserirMarcasModelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar.png"))); // NOI18N
        InserirMarcasModelos.setFocusable(false);
        InserirMarcasModelos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InserirMarcasModelos.setMaximumSize(new java.awt.Dimension(65, 45));
        InserirMarcasModelos.setMinimumSize(new java.awt.Dimension(65, 45));
        InserirMarcasModelos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        InserirMarcasModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirMarcasModelosActionPerformed(evt);
            }
        });
        jToolBar1.add(InserirMarcasModelos);
        jToolBar1.add(jSeparator2);

        EditarMarcasModelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        EditarMarcasModelos.setFocusable(false);
        EditarMarcasModelos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarMarcasModelos.setMaximumSize(new java.awt.Dimension(65, 45));
        EditarMarcasModelos.setMinimumSize(new java.awt.Dimension(65, 45));
        EditarMarcasModelos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarMarcasModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarMarcasModelosActionPerformed(evt);
            }
        });
        jToolBar1.add(EditarMarcasModelos);
        jToolBar1.add(jSeparator3);

        EliminarMarcasModelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remover.png"))); // NOI18N
        EliminarMarcasModelos.setFocusable(false);
        EliminarMarcasModelos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarMarcasModelos.setMaximumSize(new java.awt.Dimension(65, 45));
        EliminarMarcasModelos.setMinimumSize(new java.awt.Dimension(65, 45));
        EliminarMarcasModelos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarMarcasModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMarcasModelosActionPerformed(evt);
            }
        });
        jToolBar1.add(EliminarMarcasModelos);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 45));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background-menus.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 470));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 470));

        jMenu1.setText("Opções");

        jMenuItem1.setText("Inserir MarcasModelos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Editar MarcasModelos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Eliminar MarcasModelos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        InserirMarcasModelos inserirMarcasModelos = new InserirMarcasModelos();
        wallpaper.add(inserirMarcasModelos);
        inserirMarcasModelos.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        EditarMarcasModelos editarMarcasModelos = new EditarMarcasModelos();
        wallpaper.add(editarMarcasModelos);
        editarMarcasModelos.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        EliminarMarcasModelos eliminarMarcasModelos = new EliminarMarcasModelos();
        wallpaper.add(eliminarMarcasModelos);
        eliminarMarcasModelos.setVisible(true);
            
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void InserirMarcasModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirMarcasModelosActionPerformed
        
        InserirMarcasModelos inserir = new InserirMarcasModelos();
        wallpaper.add(inserir);
        inserir.setVisible(true);
        
    }//GEN-LAST:event_InserirMarcasModelosActionPerformed

    private void EditarMarcasModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarMarcasModelosActionPerformed
        
        EditarMarcasModelos editar = new EditarMarcasModelos();
        wallpaper.add(editar);
        editar.setVisible(true);
        
    }//GEN-LAST:event_EditarMarcasModelosActionPerformed

    private void EliminarMarcasModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMarcasModelosActionPerformed
        
        EliminarMarcasModelos eliminar = new EliminarMarcasModelos();
        wallpaper.add(eliminar);
        eliminar.setVisible(true);
        
    }//GEN-LAST:event_EliminarMarcasModelosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarMarcasModelos;
    private javax.swing.JButton EliminarMarcasModelos;
    private javax.swing.JButton InserirMarcasModelos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
