package Telas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Carlos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    
        setTitle("Principal");
        setSize(1200, 700);
        setLocationRelativeTo(null);
        setResizable(false);
        
        ImageIcon background = new ImageIcon("src/Imagens/pi_wallpaper.jpg");
        Icon imagem = new ImageIcon(background.getImage().getScaledInstance(wallpaper.getWidth(), wallpaper.getHeight(), Image.SCALE_DEFAULT));
        wallpaper.setIcon(imagem);
        this.repaint();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        sair = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        wallpaper = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txt_veiculos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Consulta_Placa = new javax.swing.JMenuItem();
        Consulta_Marca = new javax.swing.JMenuItem();
        Consulta_Modelo = new javax.swing.JMenuItem();
        Consulta_FaixaPreco = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/grupo.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator2);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        sair.setFocusable(false);
        sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sair.setMaximumSize(new java.awt.Dimension(60, 45));
        sair.setMinimumSize(new java.awt.Dimension(60, 45));
        sair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jToolBar1.add(sair);
        jToolBar1.add(jSeparator4);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 45));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pi_wallpaper.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 1200, 630));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 630));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Cadastro");

        txt_veiculos.setText("Veiculos");
        txt_veiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_veiculosActionPerformed(evt);
            }
        });
        jMenu1.add(txt_veiculos);

        jMenuItem2.setText("Estados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("MarcasModelos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        Consulta_Placa.setText("Por placa");
        Consulta_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_PlacaActionPerformed(evt);
            }
        });
        jMenu2.add(Consulta_Placa);

        Consulta_Marca.setText("Por marca");
        Consulta_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_MarcaActionPerformed(evt);
            }
        });
        jMenu2.add(Consulta_Marca);

        Consulta_Modelo.setText("Por modelo");
        Consulta_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_ModeloActionPerformed(evt);
            }
        });
        jMenu2.add(Consulta_Modelo);

        Consulta_FaixaPreco.setText("Por faixa de preço");
        Consulta_FaixaPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_FaixaPrecoActionPerformed(evt);
            }
        });
        jMenu2.add(Consulta_FaixaPreco);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem5.setText("Sobre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        //Para sair do sistema
        System.exit(0);
        
    }//GEN-LAST:event_sairActionPerformed

    private void txt_veiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_veiculosActionPerformed
        
        //aki apenas mandarei mostrar em um nova Interface
        Veiculos v = new Veiculos();
        wallpaper.add(v);
        v.setVisible(true);
        
    }//GEN-LAST:event_txt_veiculosActionPerformed

    private void Consulta_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_PlacaActionPerformed
        
        ConsultaPorPlaca cp = new ConsultaPorPlaca();
        wallpaper.add(cp);
        cp.setVisible(true);
        
    }//GEN-LAST:event_Consulta_PlacaActionPerformed

    private void Consulta_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_MarcaActionPerformed
        
        ConsultaPorMarca cm = new ConsultaPorMarca();
        wallpaper.add(cm);
        cm.setVisible(true);
        
    }//GEN-LAST:event_Consulta_MarcaActionPerformed

    private void Consulta_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_ModeloActionPerformed
        
        ConsultaPorModelo cpm = new ConsultaPorModelo();
        wallpaper.add(cpm);
        cpm.setVisible(true);
        
    }//GEN-LAST:event_Consulta_ModeloActionPerformed

    private void Consulta_FaixaPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_FaixaPrecoActionPerformed
        
        ConsultaPorFaixaDePreco faixaDePreco = new ConsultaPorFaixaDePreco();
        wallpaper.add(faixaDePreco);
        faixaDePreco.setVisible(true);
        
    }//GEN-LAST:event_Consulta_FaixaPrecoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        AutoresDoProjeto autores = new AutoresDoProjeto();
        wallpaper.add(autores);
        autores.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        AutoresDoProjeto autores = new AutoresDoProjeto();
        wallpaper.add(autores);
        autores.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        Estados estados = new Estados();
        wallpaper.add(estados);
        estados.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        MarcasModelos marcasModelos = new MarcasModelos();
        wallpaper.add(marcasModelos);
        marcasModelos.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consulta_FaixaPreco;
    private javax.swing.JMenuItem Consulta_Marca;
    private javax.swing.JMenuItem Consulta_Modelo;
    private javax.swing.JMenuItem Consulta_Placa;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton sair;
    private javax.swing.JMenuItem txt_veiculos;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
