package Telas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Brandon Carlos
 */
public class Veiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Veiculos
     */
    public Veiculos() {
        initComponents();
        
        setTitle("Cadastrando veiculo");
        
        /*ImageIcon background = new ImageIcon("src/Imagens/wallpaper2.jpg");
        Icon imagem = new ImageIcon(background.getImage().getScaledInstance(wallpaper.getWidth(), wallpaper.getHeight(), Image.SCALE_DEFAULT));
        wallpaper.setIcon(imagem);
        this.repaint();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        InserirVeiculo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        EditarVeiculo = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        EliminarVeiculo = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcoes = new javax.swing.JMenu();
        txt_inserir = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Eliminar_Veiculo = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        InserirVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar.png"))); // NOI18N
        InserirVeiculo.setFocusable(false);
        InserirVeiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InserirVeiculo.setMaximumSize(new java.awt.Dimension(60, 45));
        InserirVeiculo.setMinimumSize(new java.awt.Dimension(60, 45));
        InserirVeiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        InserirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirVeiculoActionPerformed(evt);
            }
        });
        jToolBar1.add(InserirVeiculo);
        jToolBar1.add(jSeparator3);

        EditarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        EditarVeiculo.setFocusable(false);
        EditarVeiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarVeiculo.setMaximumSize(new java.awt.Dimension(60, 45));
        EditarVeiculo.setMinimumSize(new java.awt.Dimension(60, 45));
        EditarVeiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarVeiculoActionPerformed(evt);
            }
        });
        jToolBar1.add(EditarVeiculo);
        jToolBar1.add(jSeparator4);

        EliminarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remover.png"))); // NOI18N
        EliminarVeiculo.setFocusable(false);
        EliminarVeiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarVeiculo.setMaximumSize(new java.awt.Dimension(65, 45));
        EliminarVeiculo.setMinimumSize(new java.awt.Dimension(65, 45));
        EliminarVeiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVeiculoActionPerformed(evt);
            }
        });
        jToolBar1.add(EliminarVeiculo);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 40));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background-menus.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 790, 470));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 470));

        opcoes.setText("Opções");

        txt_inserir.setText("Inserir veiculo");
        txt_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inserirActionPerformed(evt);
            }
        });
        opcoes.add(txt_inserir);

        jMenuItem2.setText("Editar veiculo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        opcoes.add(jMenuItem2);

        Eliminar_Veiculo.setText("Eliminar veiculo");
        Eliminar_Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_VeiculoActionPerformed(evt);
            }
        });
        opcoes.add(Eliminar_Veiculo);

        jMenuBar1.add(opcoes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inserirActionPerformed
        //Aki será aberta outra tela.
        InserirVeiculo inve = new InserirVeiculo();
        wallpaper.add(inve);
        inve.setVisible(true);
    }//GEN-LAST:event_txt_inserirActionPerformed

    private void InserirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirVeiculoActionPerformed
        
        InserirVeiculo insve = new InserirVeiculo();
        wallpaper.add(insve);
        insve.setVisible(true);   
    }//GEN-LAST:event_InserirVeiculoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        EditarVeiculo editar = new EditarVeiculo();
        wallpaper.add(editar);
        editar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void Eliminar_VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_VeiculoActionPerformed
        
        EliminarVeiculo ev = new EliminarVeiculo();
        wallpaper.add(ev);
        ev.setVisible(true);
        
    }//GEN-LAST:event_Eliminar_VeiculoActionPerformed

    private void EditarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarVeiculoActionPerformed
        EditarVeiculo editarVeiculo = new EditarVeiculo();
        wallpaper.add(editarVeiculo);
        editarVeiculo.setVisible(true);
    }//GEN-LAST:event_EditarVeiculoActionPerformed

    private void EliminarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVeiculoActionPerformed
        EliminarVeiculo eliminarVeiculo = new EliminarVeiculo();
        wallpaper.add(eliminarVeiculo);
        eliminarVeiculo.setVisible(true);
    }//GEN-LAST:event_EliminarVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarVeiculo;
    private javax.swing.JButton EliminarVeiculo;
    private javax.swing.JMenuItem Eliminar_Veiculo;
    private javax.swing.JButton InserirVeiculo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu opcoes;
    private javax.swing.JMenuItem txt_inserir;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
